### ISSUE TITLE
Crash with agricraft mod on startup

### ISSUE THREAD

**Issue by quentin452** [DylanLogan2581/AncientWarfare3#2] opened 2022-10-11 07:14 UTC
I don't crash when i use ancient warfare 2

crash report : 

[crash-2022-10-11_09.14.19-client.txt](https://github.com/DylanLogan2581/AncientWarfare3/files/9752073/crash-2022-10-11_09.14.19-client.txt)

mods list :

AgriCraft-1.7.10-1.5.0
ancientwarfare-3.0.1-beta-MC1.7.10-FULL

**Comment by DylanLogan2581** [comment] 2022-12-22 21:43
This is a duplicate of #1. Closing as a duplicate. This will be fixed, check there.

**Closed as not planned** 2022-12-22 21:43 UTC
Labels: duplicate
